/* Derived opportunity scoring. This is a viewer-side model, never canonical master state. */
(function(root, factory){
  'use strict';
  if(typeof module==='object'&&module.exports)module.exports=factory();
  else root.PipelineScoring=factory();
}(typeof self!=='undefined'?self:this,function(){
  'use strict';
  var Policy=typeof module==='object'&&module.exports?require('./pipeline-policy'):PipelinePolicy;
  var STATES={AL:[32.8,-86.8],AK:[64.2,-152],AZ:[34.3,-111.7],AR:[34.9,-92.4],CA:[36.8,-119.4],CO:[39,-105.5],CT:[41.6,-72.7],DE:[39,-75.5],FL:[27.8,-81.7],GA:[32.7,-83.3],IA:[42,-93.5],ID:[44.1,-114.7],IL:[40,-89.2],IN:[40,-86.1],KS:[38.5,-98],KY:[37.8,-85.8],LA:[31,-92],MA:[42.3,-71.8],MD:[39,-76.7],ME:[45.3,-69],MI:[44.3,-85.6],MN:[46.3,-94.2],MO:[38.5,-92.5],MS:[32.7,-89.7],MT:[46.9,-110.4],NC:[35.5,-79.4],ND:[47.4,-100.5],NE:[41.5,-99.8],NH:[43.7,-71.6],NJ:[40.1,-74.7],NM:[34.5,-106],NV:[39.3,-116.6],NY:[42.9,-75.5],OH:[40.4,-82.8],OK:[35.6,-97.5],OR:[44,-120.5],PA:[40.9,-77.8],RI:[41.7,-71.5],SC:[33.8,-80.9],SD:[44.4,-100.2],TN:[35.8,-86.4],TX:[31.5,-99.3],UT:[39.3,-111.7],VA:[37.5,-78.7],VT:[44,-72.7],WA:[47.4,-120.7],WI:[44.6,-89.6],WV:[38.6,-80.6],WY:[43,-107.6]};
  var CITY={
    'cleveland, tn':[35.1595,-84.8766],'chattanooga, tn':[35.0456,-85.3097],'tampa, fl':[27.9506,-82.4572],
    'detroit, mi':[42.3314,-83.0458],'lansing, mi':[42.7325,-84.5555],'grand rapids, mi':[42.9634,-85.6681],
    'new york, ny':[40.7128,-74.006],'los angeles, ca':[34.0522,-118.2437],'san francisco, ca':[37.7749,-122.4194],
    'seattle, wa':[47.6062,-122.3321],'portland, or':[45.5152,-122.6784],'austin, tx':[30.2672,-97.7431],
    'dallas, tx':[32.7767,-96.797],'phoenix, az':[33.4484,-112.074],'huntsville, al':[34.7304,-86.5861],
    'nashville, tn':[36.1627,-86.7816],'knoxville, tn':[35.9606,-83.9207],'chicago, il':[41.8781,-87.6298]
  };
  var DEFAULT_KEYWORDS=['manufacturing','quality','operations','production','industrialization','launch','startup','greenfield','plant','process engineering','manufacturing engineering','torque','fastening','tool systems','tooling','dc electric','automation','robotics','ev','battery','supplier quality','continuous improvement','apqp','equipment','commissioning','validation','root cause','change control','plant floor','leader'];
  function defaults(){return normalize({weights:{experience:15,flex:10,compensation:20,geo:20,ats:15,title:10,culture:5,ownership:5},geo:{power:2,controlPoints:[
    {name:'Cleveland, TN',lat:35.1595,lon:-84.8766,score:100,hard:false},
    {name:'New York, NY',lat:40.7128,lon:-74.006,score:0,hard:true},
    {name:'Tampa, FL',lat:27.9506,lon:-82.4572,score:70,hard:false},
    {name:'Detroit, MI',lat:42.3314,lon:-83.0458,score:5,hard:false},
    {name:'Los Angeles, CA',lat:34.0522,lon:-118.2437,score:20,hard:false},
    {name:'San Francisco, CA',lat:37.7749,lon:-122.4194,score:20,hard:false},
    {name:'Seattle, WA',lat:47.6062,lon:-122.3321,score:20,hard:false}
  ]},salary:{floor:160000,target:220000,ceiling:320000,stateFactors:{TN:1,FL:1.02,MI:.9,NY:.72,CA:.82,WA:.9,OR:.84}},resumeKeywords:DEFAULT_KEYWORDS.join(', ')});}
  function clamp(n,a,b){return Math.max(a,Math.min(b,n))}
  function num(v){var n=parseFloat(String(v==null?'':v).replace(/[$,%s,]/g,''));return isFinite(n)?n:null}
  function scoreValue(v){var n=num(v);if(n!=null)return clamp(n<=1?n*100:n,0,100);var s=String(v||'').toUpperCase();if(/VERY HIGH|EXCELLENT|STRONG|HIGH|YES|GOOD|MATCH/.test(s))return 90;if(/MEDIUM|MODERATE|PARTIAL|SOFT/.test(s))return 65;if(/LOW|WEAK|POOR|NO|MISMATCH|STRICT/.test(s))return 20;return null}
  function normalize(c){var d=defaultsBare(),x=c||{};d.weights=Object.assign(d.weights,x.weights||{});d.geo=Object.assign(d.geo,x.geo||{});d.geo.controlPoints=Array.isArray(x.geo&&x.geo.controlPoints)?x.geo.controlPoints:d.geo.controlPoints;d.salary=Object.assign(d.salary,x.salary||{});d.salary.stateFactors=Object.assign(d.salary.stateFactors,(x.salary&&x.salary.stateFactors)||{});d.resumeKeywords=String(x.resumeKeywords||d.resumeKeywords);return d}
  function defaultsBare(){return {weights:{experience:15,flex:10,compensation:20,geo:20,ats:15,title:10,culture:5,ownership:5},geo:{power:2,controlPoints:[]},salary:{floor:160000,target:220000,ceiling:320000,stateFactors:{}},resumeKeywords:DEFAULT_KEYWORDS.join(', ')}}
  function stateCode(s){var t=String(s||'').trim(),m=t.match(/(?:,|\s)\s*([A-Z]{2})(?:\b|$)/i);if(m&&STATES[m[1].toUpperCase()])return m[1].toUpperCase();var low=t.toLowerCase(),names={alabama:'AL',alaska:'AK',arizona:'AZ',arkansas:'AR',california:'CA',colorado:'CO',connecticut:'CT',delaware:'DE',florida:'FL',georgia:'GA',idaho:'ID',illinois:'IL',indiana:'IN',iowa:'IA',kansas:'KS',kentucky:'KY',louisiana:'LA',maine:'ME',maryland:'MD',massachusetts:'MA',michigan:'MI',minnesota:'MN',mississippi:'MS',missouri:'MO',montana:'MT',nebraska:'NE',nevada:'NV','new hampshire':'NH','new jersey':'NJ','new mexico':'NM','new york':'NY','north carolina':'NC','north dakota':'ND',ohio:'OH',oklahoma:'OK',oregon:'OR',pennsylvania:'PA','rhode island':'RI','south carolina':'SC','south dakota':'SD',tennessee:'TN',texas:'TX',utah:'UT',vermont:'VT',virginia:'VA',washington:'WA','west virginia':'WV',wisconsin:'WI',wyoming:'WY'};for(var k in names)if(low.indexOf(k)>=0)return names[k];return ''}
  function point(r){var p=r&&r.payload||{},lat=num(p.LATITUDE||p.LAT),lon=num(p.LONGITUDE||p.LON||p.LNG);if(lat!=null&&lon!=null)return{lat:lat,lon:lon,state:stateCode(r.LOCATION)};var label=String(r.LOCATION||p.LOCATION||'').toLowerCase().replace(/\s+/g,' ').trim(),cache=null;try{cache=JSON.parse(localStorage.getItem('px.geoCache')||'{}')[label]}catch(e){}if(cache&&num(cache.lat)!=null&&num(cache.lon)!=null)return{lat:+cache.lat,lon:+cache.lon,state:stateCode(r.LOCATION)};var city=label.split(',').slice(0,2).join(',').trim();if(CITY[city])return{lat:CITY[city][0],lon:CITY[city][1],state:stateCode(r.LOCATION)};var sc=stateCode(r.LOCATION),c=STATES[sc];return c?{lat:c[0],lon:c[1],state:sc,approx:true}:null}
  function hav(a,b,c,d){var R=3958.8,rad=Math.PI/180,la=(c-a)*rad,lo=(d-b)*rad,x=Math.sin(la/2)*Math.sin(la/2)+Math.cos(a*rad)*Math.cos(c*rad)*Math.sin(lo/2)*Math.sin(lo/2);return 2*R*Math.asin(Math.sqrt(x))}
  function text(r){var p=r&&r.payload||{},a=[r&&r.TITLE,r&&r.COMPANY,r&&r.LOCATION,r&&r.raw];Object.keys(p).forEach(function(k){a.push(p[k])});return a.join(' ').toLowerCase()}
  function keywords(c){return String(c.resumeKeywords||'').split(/[,;\n]+/).map(function(s){return s.trim().toLowerCase()}).filter(function(s){return s.length>2})}
  function keywordScore(r,c){var ks=keywords(c),t=text(r),hits=ks.filter(function(k){return t.indexOf(k)>=0});if(!ks.length||!t.trim())return{score:null,known:false,basis:'No resume profile or role text'};var s=clamp(35+(hits.length/Math.max(1,Math.min(ks.length,12)))*65,0,100);return{score:Math.round(s),known:true,basis:hits.slice(0,8).join(', ')||'No strong keyword overlap',hits:hits}}
  function experience(r,c){var p=r.payload||{},explicit=scoreValue(p.SCOPE_FIT_RAW||p.RAW_FIT||p.EXPERIENCE_FIT_SCORE||p.EXPERIENCE_FIT||p.FIT_SCORE||p.FIT_PCT||p.WORK_CONTENT_FIT||p.FIT);if(explicit!=null)return{score:Math.round(explicit),known:true,basis:p.EXPERIENCE_FIT_BASIS||p.FIT_BASIS||'Existing role-fit evidence'};var k=keywordScore(r,c);return{score:k.score,known:k.known,basis:k.basis}}
  function title(r){var p=r.payload||{},e=scoreValue(p.TITLE_FIT||p.LEVEL_FIT||p.TITLE_SCORE);if(e!=null)return{score:Math.round(e),known:true,basis:'Explicit title-fit evidence'};var t=String(r.TITLE||'');if(!t)return{score:null,known:false,basis:'Title missing'};var s=/\b(chief|vp|vice president|head|director|general manager|plant manager)\b/i.test(t)?90:/\b(manager|senior manager|lead)\b/i.test(t)?75:/\b(engineer|quality|operations|manufacturing|production)\b/i.test(t)?65:45;return{score:s,known:true,basis:'Title level heuristic'}}
  function compensation(r,c){var mid=num(r.compMid);if(mid==null){var p=r.payload||{},m=String(p.SALARY_BASE_POSTED||p.PAY_POSTED||p.SALARY_BASE_EST||'').match(/\$?\s*([\d,.]+)\s*([kK])?/);if(m){mid=parseFloat(m[1].replace(/,/g,''))*(m[2]?1000:1);if(mid<1000)mid*=1000}}if(mid==null)return{score:null,known:false,basis:'Salary missing'};var sc=stateCode(r.LOCATION),factor=num(c.salary.stateFactors[sc])||1,net=mid*factor,floor=num(c.salary.floor)||150000,target=num(c.salary.target)||220000,ceil=num(c.salary.ceiling)||320000,s=net<=floor?0:net>=ceil?100:(net-floor)/(ceil-floor)*100;return{score:Math.round(clamp(s,0,100)),known:true,basis:'Salary midpoint × configurable state net-value factor',mid:mid,state:sc,factor:factor}}
  function geoScoreAt(lat,lon,c){var ps=c.geo.controlPoints||[];if(num(lat)==null||num(lon)==null||!ps.length)return{score:null,known:false,basis:'Location not geocoded'};var exact=ps.filter(function(x){return hav(+lat,+lon,+x.lat,+x.lon)<15});if(exact.length)return{score:Math.round(clamp(num(exact[0].score)||0,0,100)),known:true,basis:exact[0].name+(exact[0].hard?' hard override':'')};var power=num(c.geo.power)||2,wSum=0,sSum=0,nearest=null;ps.forEach(function(x){var d=hav(+lat,+lon,+x.lat,+x.lon);if(!isFinite(d))return;if(!nearest||d<nearest.d)nearest={d:d,x:x};var w=1/Math.pow(Math.max(d,1),power);wSum+=w;sSum+=w*clamp(num(x.score)||0,0,100)});return{score:wSum?Math.round(clamp(sSum/wSum,0,100)):null,known:!!wSum,basis:'Distance-weighted interpolation; nearest '+(nearest&&nearest.x.name||'control point')}}
  function geo(r,c){var pt=point(r);if(!pt)return{score:null,known:false,basis:'Location not geocoded'};var out=geoScoreAt(pt.lat,pt.lon,c);if(out.known&&pt.approx)out.basis+=' · state centroid';return out}
  function explicit(r,keys){var p=r.payload||{};for(var i=0;i<keys.length;i++){var s=scoreValue(p[keys[i]]);if(s!=null)return{score:Math.round(s),known:true,basis:'Explicit '+keys[i]};}return{score:50,known:false,basis:'No evidence recorded · neutral placeholder'}}
  function ats(r,c){var p=r.payload||{},e=scoreValue(p.ATS_MATCH_SCORE||p.RESUME_MATCH_SCORE||p.ATS_SCORE);var k=keywordScore(r,c),s=e!=null?Math.round(e):k.score;if(s==null)return{score:null,known:false,gate:'UNKNOWN',basis:'No role text or ATS evidence'};var gate=String(p.SCREEN_GATE||p.ATS_GATE||'').toUpperCase();if(!gate)gate=s>=75?'PASS':s>=55?'RISK':'FAIL';var degree=String(p.DEGREE_REQ||p.DEGREE||'').toUpperCase();if(/REQUIRED|BACHELOR|MASTER|DEGREE/.test(degree)&&!String(c.resumeKeywords||'').toLowerCase().match(/bachelor|master|degree/))gate=gate==='PASS'?'RISK':gate;return{score:s,known:true,gate:gate,basis:e!=null?'Explicit ATS score':('Keyword proxy · '+(k.basis||'no overlap'))}}
  function flexScore(f){var cls=f&&f.class||'UNKNOWN';if(cls==='HIGH_FLEX')return 80;if(cls==='SOFT_FLEX')return 62;if(cls==='NO_FLEX')return 30;if(cls==='STRICT')return 0;return 50}
  function band(s){return s==null?'UNKNOWN':s>=90?'PRIORITY':s>=75?'STRONG':s>=60?'WATCH':s>=40?'WEAK':'NO-GO'}
  function scoreRow(r,cfg){var c=normalize(cfg),parts={experience:experience(r,c),compensation:compensation(r,c),geo:geo(r,c),ats:ats(r,c),title:title(r),culture:explicit(r,['CULTURE_SCORE','COMPANY_CULTURE_SCORE']),ownership:explicit(r,['OWNERSHIP_SCORE','COMPANY_OWNERSHIP_SCORE'])},assessment=Policy.assess(r.payload||{},parts.experience.score),sum=0,rawSum=0,avail=0,total=0;parts.experience=Object.assign({},parts.experience,{rawScore:parts.experience.score,adjustedScore:assessment.adjustedFit,flexModifier:assessment.flex.modifier,basis:parts.experience.basis});parts.flex={score:flexScore(assessment.flex),known:assessment.flex.known,basis:assessment.flex.class+' · '+(assessment.flex.modifier>=0?'+':'')+assessment.flex.modifier+' degree-flex modifier'};Object.keys(c.weights).forEach(function(k){var w=Math.max(0,num(c.weights[k])||0);total+=w;if(parts[k]&&parts[k].known){sum+=w*parts[k].score;rawSum+=w*(k==='flex'?50:(k==='experience'&&assessment.rawFit!=null?assessment.rawFit:parts[k].score));avail+=w}});var raw=avail?sum/avail:null,rawWithoutFlex=avail?rawSum/avail:null,confidence=total?Math.round(avail/total*100):0,overall=raw==null?null:Math.round(raw*(.7+.3*confidence/100)),overallWithoutFlex=rawWithoutFlex==null?null:Math.round(rawWithoutFlex*(.7+.3*confidence/100));return{overall:overall,overallWithoutFlex:overallWithoutFlex,flexInfluence:overall==null||overallWithoutFlex==null?0:overall-overallWithoutFlex,band:assessment.flex.blocked?'STRICT HOLD':band(overall),assessment:assessment,confidence:confidence,parts:parts,screenGate:parts.ats.gate||'UNKNOWN',ratingBasis:'Derived viewer model; raw content fit and degree FLEX are separate weighted inputs; canonical master unchanged'} }
  return{defaults:defaults,normalize:normalize,scoreRow:scoreRow,stateCode:stateCode,point:point,geoScoreAt:geoScoreAt,keywords:keywords,states:STATES};
}));
