'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const A=require('../pipeline-alignment'),Adapter=require('../pipeline-automation-adapter'),Writer=require('../apps-script/Code.gs');
const at='2026-10-09T12:00:00Z',scope={sources:['assigned Gmail query'],windowPolicy:'since last independently verified checkpoint',assignmentEvidence:'approved-native-readback',maxMessagesPerBatch:5};
const schedule={timezone:'America/New_York',rule:'existing'};
function fixture(){const task=A.task('forge-email'),authorities={common:{ok:true,id:A.IDS.common,active:true,fingerprint:'c',fetchedAt:at},rules:{ok:true,id:A.IDS.rules,active:true,fingerprint:'r',fetchedAt:at},reason:{ok:true,owner:'FORGE',id:'assigned-AI_REASON',fingerprint:'reason',fetchedAt:at},writer:{ok:true,masterId:A.IDS.master,fingerprint:'w',fetchedAt:at}};return {taskKey:task.key,attemptId:'run1',at,scope,approvedSchedule:schedule,authorities,native:{provider:task.provider,taskId:task.nativeId,prompt:A.prompt(task,scope),enabled:true,schedule,evidenceRef:'native-readback',readbackAt:at},capabilities:{checkpoint:true,writerTransport:true,coverageReadback:true}};}
function harness(){let f=fixture(),writes=0,updates=0;const records=new Map();const io={now:()=>Date.parse(at),readAuthorities:async()=>f.authorities,verifyCoverage:async()=>({verified:true,evidenceRef:'independent ledger readback'}),persist:async r=>records.set(r.attemptId,structuredClone(r)),readCheckpoint:async id=>records.get(id),provider:{getTask:async()=>structuredClone(f.native),updatePrompt:async(id,x)=>{updates++;f.native.prompt=x.prompt;throw Error('lost response')}},submitWriter:async()=>{writes++;return {ok:true}},reconcileWriter:async()=>({state:'VERIFIED_COMPLETE',receiptId:'receipt',masterReadbackRef:'fresh exact row'})};return {f,io,records,writes:()=>writes,updates:()=>updates};}
const complete={scopeKnown:true,coverageEvidenceRef:'page/body/link ledger',plannedUnits:5,examinedUnits:5,foundCandidates:1,disposedCandidates:1,pendingWrites:0,carryForward:0,independentDispositions:true,sourcePaginationComplete:true};
test('fresh complete contract passes; schedule object key ordering is immaterial',()=>{let f=fixture();f.native.schedule={rule:'existing',timezone:'America/New_York'};assert.equal(A.preflight(f).allowed,true)});
test('unreadable/stale/inactive authority fails closed',()=>{for(const change of [f=>f.authorities.rules.ok=false,f=>f.authorities.common.fetchedAt='2026-10-08T00:00:00Z',f=>f.authorities.common.active=false]){const f=fixture();change(f);assert.equal(A.preflight(f).allowed,false)}});
test('prompt override and wrong master produce exact conflicts',()=>{const f=fixture();f.native.prompt+='\nUse +15 FLEX';f.authorities.writer.masterId='rollback';const r=A.preflight(f);assert.equal(r.state,'PAUSED_CONFLICT');assert.ok(r.issues.some(i=>i.actual.endsWith&&i.actual.endsWith('Use +15 FLEX')))});
test('unknown native adoption and unassigned scope cannot run',()=>{const f=fixture();f.native=null;assert.equal(A.preflight(f).state,'NATIVE_ADOPTION_UNVERIFIED');f.scope=null;assert.equal(A.preflight(f).state,'BLOCKED_SCOPE')});
test('Claude requires explicit native identity enrollment',()=>{const f=fixture(),t=A.task('claude-analysis');f.taskKey=t.key;f.authorities.reason.owner=t.owner;f.native={...f.native,provider:t.provider,taskId:'actual-claude-id',prompt:A.prompt(t,scope)};assert.equal(A.preflight(f).state,'BLOCKED_SCOPE');f.nativeTaskId='actual-claude-id';assert.equal(A.preflight(f).allowed,true)});
test('lane cannot change decisions or impersonate another owner',()=>{const r=A.preflight(fixture());assert.throws(()=>A.assertRequest(r,{action:'ruling',ruling:{kind:'ENRICH'}}),/LANE/);assert.throws(()=>A.assertRequest(r,{action:'intake',actor:'GROK'}),/OWNER/)});
test('run completion requires full scope, pagination and evidence',()=>{assert.equal(A.completion(complete).state,'VERIFIED_COMPLETE');for(const patch of [{examinedUnits:4},{disposedCandidates:0},{sourcePaginationComplete:false},{carryForward:1},{coverageEvidenceRef:''}])assert.notEqual(A.completion({...complete,...patch}).state,'VERIFIED_COMPLETE')});
test('lost native update response uses readback once, preserves schedule',async()=>{const h=harness();h.f.native.revision='original';h.f.native.prompt='old';const r=await Adapter.create(h.io).updatePrompt('forge-email',scope,'update1');assert.equal(r.state,'PROMPT_READBACK_MATCH');assert.equal(h.updates(),1);assert.deepEqual(r.after.schedule,schedule)});
test('paused native task is never reactivated',async()=>{const h=harness();h.f.native.enabled=false;await assert.rejects(Adapter.create(h.io).updatePrompt('forge-email',scope,'update1'),/REACTIVATION/);assert.equal(h.updates(),0)});
test('checkpoint failure prevents provider and Writer changes',async()=>{const h=harness();h.io.persist=async()=>{throw Error('disk unavailable')};await assert.rejects(Adapter.create(h.io).execute(h.f,async c=>c.submit({action:'intake',requestId:'x'})),/disk/);assert.equal(h.writes(),0)});
test('stable request recovery across attempts never resends and rejects changed body',async()=>{const h=harness(),a=Adapter.create(h.io),body={action:'intake',requestId:'stable',actor:'FORGE'};const work=async c=>{await c.submit(body);return {...complete}};await a.execute(h.f,work);await a.execute({...h.f,attemptId:'run2'},work);assert.equal(h.writes(),1);await assert.rejects(a.execute({...h.f,attemptId:'run3'},async c=>c.submit({...body,actor:'forge'})),/BODY_CONFLICT/)});
test('authority drift between run start and write prevents submission',async()=>{const h=harness();await assert.rejects(Adapter.create(h.io).execute(h.f,async c=>{h.f.authorities.rules.ok=false;await c.submit({action:'intake',requestId:'x'})}),/PREFLIGHT/);assert.equal(h.writes(),0)});
test('transport ambiguity cannot yield complete from worker claims',async()=>{const h=harness();h.io.submitWriter=async()=>{throw Error('response lost')};const r=await Adapter.create(h.io).execute(h.f,async c=>{await c.submit({action:'intake',requestId:'x'});return {...complete}});assert.equal(r.state,'PARTIAL');assert.equal(h.records.get('writer:x').state,'POSTCOMMIT_UNKNOWN')});
test('Writer rejects stale envelope or forbidden lane before touching master',()=>{const f=fixture(),req={action:'intake',requestId:'x',automation:{taskKey:f.taskKey,attemptId:f.attemptId,authorityFingerprints:{common:'c',rules:'r',writer:'w'}}};assert.equal(Writer.automationEnvelopeError_(req,{authorities:f.authorities}),'');req.automation.authorityFingerprints.rules='old';assert.match(Writer.automationEnvelopeError_(req,{authorities:f.authorities}),/AUTHORITY_CHANGED/)});
test('research prompt uses current policy values and rejects unknown modifiers',()=>{assert.match(A.discoveryInstructions({HIGH_FLEX_MODIFIER:30,SOFT_FLEX_MODIFIER:20,NO_FLEX_MODIFIER:-10,STRICT_MODIFIER:-30}),/HIGH_FLEX \+30, SOFT_FLEX \+20/);assert.throws(()=>A.discoveryInstructions({}),/POLICY/)});
test('Apps Script contract is byte-identical to shared contract',()=>{const fs=require('fs');assert.equal(fs.readFileSync('pipeline-alignment.js','utf8'),fs.readFileSync('apps-script/PipelineAlignment.gs','utf8'))});

test('worker completion claim fails when independent ledger cannot verify coverage',async()=>{const h=harness();h.io.verifyCoverage=async()=>({verified:false});const r=await Adapter.create(h.io).execute(h.f,async()=>({...complete}));assert.equal(r.state,'UNKNOWN')});

test('unreadable authority blocks native prompt correction too',async()=>{const h=harness();h.f.native.revision='v1';h.f.authorities.rules.ok=false;await assert.rejects(Adapter.create(h.io).updatePrompt('forge-email',scope,'u'),/UPDATE_BLOCKED/);assert.equal(h.updates(),0)});
