const test=require('node:test'),assert=require('node:assert/strict');
const {createService,normalizeUrl,jobId}=require('../netlify/lib/manual-intake.cjs');
function fixture(){const records=new Map();let serial=0,stamp='2026-10-02T17:00:00Z',rows=[];const store={get:async k=>records.get(k)?.data||null,getWithMetadata:async k=>records.get(k)||null,setJSON:async(k,data,opts={})=>{const old=records.get(k);if(opts.onlyIfNew&&old||opts.onlyIfMatch&&old?.etag!==opts.onlyIfMatch)return {modified:false};records.set(k,{data:structuredClone(data),etag:String(++serial)});return {modified:true}},async *list(){yield {blobs:[...records.keys()].filter(k=>k.startsWith('items/')).map(key=>({key}))}}};return {call:createService({store,readMaster:async()=>({rows}),now:()=>stamp}),setRows:r=>rows=r,setTime:t=>stamp=t,records}}
const url='https://jobs.example.com/positions/123';
test('Canonical URL deduplicates tracking parameters; rejects invalid links',()=>{assert.equal(normalizeUrl(url+'?utm_source=a#top'),url);assert.equal(jobId(url),jobId(url+'?utm_medium=email'));assert.throws(()=>normalizeUrl('javascript:alert(1)'));assert.throws(()=>normalizeUrl('http://127.0.0.1/x'))});
test('Concurrent submissions retain one shared record, preserve application claim and unknown date',async()=>{const f=fixture();const result=await Promise.all([f.call('submit',{url,applicationStatus:'APPLIED'}),f.call('submit',{url:url+'?utm_source=b',notes:'Research lead'})]);assert.equal(result.filter(r=>r.duplicate).length,1);const list=await f.call('list');assert.equal(list.counts.TOTAL,1);assert.equal(list.items[0].applicationStatus,'APPLIED');assert.equal(list.items[0].appliedDate,'');assert.equal(list.items[0].notes,'Research lead');assert.equal(list.counts.WAITING,1);assert.throws(()=>normalizeUrl('ftp://example.com/x'));await assert.rejects(()=>f.call('submit',{url,appliedDate:'2026-02-30'}),/real/)});
test('Lease required, concurrent claims blocked, public token hidden, expired lease reclaimable',async()=>{const f=fixture(),{item}=await f.call('submit',{url});await assert.rejects(()=>f.call('progress',{id:item.id,status:'RESEARCHING'}),/lease/);const claim=await f.call('claim',{id:item.id});assert(claim.token);assert.equal(claim.item.lease.token,undefined);await assert.rejects(()=>f.call('claim',{id:item.id}),/Another worker/);await assert.rejects(()=>f.call('progress',{id:item.id,token:claim.token,status:'ADDED'}),/readback/);f.setTime('2026-10-02T19:00:00Z');await assert.rejects(()=>f.call('progress',{id:item.id,token:claim.token}),/expired/);assert((await f.call('claim',{id:item.id})).token!==claim.token)});
test('Link requires matching fresh canonical row and protected already-applied status',async()=>{const f=fixture(),{item}=await f.call('submit',{url,applicationStatus:'APPLIED'}),{token}=await f.call('claim',{id:item.id});await assert.rejects(()=>f.call('link',{id:item.id,token,primaryId:'V2-test'}),/not found/);f.setRows([{PRIMARY_ID:'V2-test',BUCKET:'SCOUT_INTAKE',payload:{SOURCE_URL:url}}]);await assert.rejects(()=>f.call('link',{id:item.id,token,primaryId:'V2-test'}),/Already-applied/);f.setRows([{PRIMARY_ID:'V2-test',BUCKET:'APPLIED',payload:{SOURCE_URL:url}}]);const linked=await f.call('link',{id:item.id,token,primaryId:'V2-test'});assert(linked.readbackVerified);assert.equal(linked.item.status,'ADDED');assert.equal((await f.call('list')).counts.IN_MASTER,1);assert.equal((await f.call('list')).items[0].masterStage,'applied')});
test('Failed research retains history, explicit retry, exclusions require rule, identity mismatch never links',async()=>{const f=fixture(),{item}=await f.call('submit',{url}),c=await f.call('claim',{id:item.id});await assert.rejects(()=>f.call('progress',{id:item.id,token:c.token,status:'EXCLUDED'}),/rule ID/);f.setRows([{PRIMARY_ID:'V2-other',COMPANY:'Other',TITLE:'Other',BUCKET:'SCOUT_INTAKE',payload:{SOURCE_URL:'https://example.org/other'}}]);await assert.rejects(()=>f.call('link',{id:item.id,token:c.token,primaryId:'V2-other'}),/does not match/);await f.call('progress',{id:item.id,token:c.token,status:'NEEDS_INFO',phase:'Source inaccessible',detail:'Need a public job description'});assert.equal((await f.call('list')).counts.NEEDS_INFO,1);assert.equal((await f.call('retry',{id:item.id})).item.status,'QUEUED');assert.equal((await f.call('list')).items[0].history.length,4)});
