'use strict';
const fs=require('fs'),path=require('path'),http=require('http'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PIPELINE_PLAYWRIGHT_MODULE||'playwright');
const repo=path.resolve(__dirname,'..'),out=process.env.PIPELINE_UI_ARTIFACTS||'/tmp/pipeline-motion';fs.mkdirSync(out,{recursive:true});
const fixture=require('./gen_population').generate(600,70);
(async()=>{
 const server=http.createServer((req,res)=>{const file=path.resolve(repo,'.'+new URL(req.url,'http://localhost').pathname);if(!file.startsWith(repo+'/'))return res.writeHead(403).end();try{res.setHeader('Content-Type',file.endsWith('.js')?'application/javascript':file.endsWith('.css')?'text/css':'text/html');res.end(fs.readFileSync(file))}catch(e){res.writeHead(404).end()}});
 await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;
 try{
  browser=await chromium.launch({headless:true,executablePath:process.env.PIPELINE_CHROMIUM,args:['--no-sandbox']});
  const context=await browser.newContext({viewport:{width:1440,height:900}}),page=await context.newPage(),errors=[],writes=[];let delayRead=false;
  page.on('pageerror',e=>errors.push(e.message));
  await page.addInitScript(()=>localStorage.setItem('px.cfg',JSON.stringify({url:location.origin+'/writer',key:'synthetic-only'})));
  await page.route('**/*',async route=>{const req=route.request(),u=new URL(req.url());if(u.hostname!=='127.0.0.1')return route.abort();if(u.pathname!=='/writer')return route.continue();if(req.method()!=='GET'){writes.push(JSON.parse(req.postData()).action);return route.fulfill({json:{ok:false,error:'Preview forbids writes'}})}const action=u.searchParams.get('action');if(action==='master'&&delayRead)await new Promise(r=>setTimeout(r,1200));let j={ok:true};if(action==='master')j={ok:true,text:fixture,id:'synthetic-only',fetchedAt:new Date().toISOString()};else if(action==='state')j={ok:true,state:{}};else if(action==='canonical_rules')j={ok:true,text:fs.readFileSync(repo+'/tests/fixtures/TIM_PIPELINE_RULES_CANONICAL.sample.txt','utf8')};else if(action==='writer_status')j={ok:true,level:'ok',warnings:[],queue:{processing:[]},unverified:{pending:[]}};await route.fulfill({json:j});});
  await page.goto('http://127.0.0.1:'+server.address().port+'/pipeline.html');
  await page.waitForSelector('#grid tbody tr[data-id]');await page.waitForTimeout(900);
  const cdp=await context.newCDPSession(page),frames=[];
  cdp.on('Page.screencastFrame',event=>{frames.push({time:event.metadata.timestamp,data:event.data});cdp.send('Page.screencastFrameAck',{sessionId:event.sessionId}).catch(()=>{});});
  await cdp.send('Page.startScreencast',{format:'jpeg',quality:85,maxWidth:1440,maxHeight:900,everyNthFrame:1});
  const observations={};
  await page.locator('#grid tbody tr[data-id]').nth(2).click();
  observations.selectedAnimations=await page.locator('#drawer').evaluate(e=>e.getAnimations({subtree:true}).filter(a=>a.playState==='running').length);
  assert(observations.selectedAnimations>0,'Selection should animate');
  const ring=page.locator('.ws-ring'),actual=await ring.evaluate(e=>+e.style.getPropertyValue('--pct'));
  assert((await ring.evaluate(e=>+getComputedStyle(e).getPropertyValue('--pct')))<actual,'Ring should sweep to the actual value');
  await page.waitForTimeout(850);
  assert.equal(await ring.evaluate(e=>+getComputedStyle(e).getPropertyValue('--pct')),actual);
  await page.locator('[data-dtab="fit"]').click();await page.waitForTimeout(950);
  await page.locator('[data-dtab="application"]').click();await page.waitForTimeout(950);
  await page.locator('[data-dtab="overview"]').click();await page.waitForTimeout(450);
  await page.locator('#edit-note').focus();await page.locator('#edit-note').scrollIntoViewIfNeeded();await page.waitForTimeout(1000);
  assert.equal(await page.locator('#edit-note').evaluate(e=>getComputedStyle(e).outlineStyle),'solid');
  await page.locator('#d-body').evaluate(e=>e.scrollTop=0);
  const divider=page.locator('#list-map-divider'),b=await divider.boundingBox();
  await divider.hover();await page.waitForTimeout(850);
  await page.mouse.move(b.x+b.width/2,b.y+b.height/2);await page.mouse.down();await page.mouse.move(b.x+b.width/2,b.y-85,{steps:18});await page.mouse.up();await page.waitForTimeout(750);
  await divider.dblclick();await page.mouse.move(700,400);await page.waitForTimeout(650);
  await page.locator('#grid tbody tr[data-id]').nth(5).click();await page.waitForTimeout(1000);
  delayRead=true;await page.locator('#refresh').click();
  await page.waitForFunction(()=>document.body.dataset.freshness==='loading');
  assert.equal(await page.locator('#gridpane').getAttribute('aria-busy'),'true');
  await page.waitForFunction(()=>document.body.dataset.freshness==='live');
  assert.equal(await page.locator('#gridpane').getAttribute('aria-busy'),'false');await page.waitForTimeout(850);
  await page.screenshot({path:out+'/motion-desktop.png'});
  await cdp.send('Page.stopScreencast');
  const frameDir=path.join(out,'frames');fs.mkdirSync(frameDir,{recursive:true});
  frames.forEach((f,i)=>fs.writeFileSync(path.join(frameDir,'frame-'+String(i).padStart(5,'0')+'.jpg'),Buffer.from(f.data,'base64')));
  fs.writeFileSync(path.join(out,'frames.ffconcat'),'ffconcat version 1.0\n'+frames.map((f,i)=>"file 'frames/frame-"+String(i).padStart(5,'0')+".jpg'\nduration "+(i+1<frames.length?Math.max(.01,frames[i+1].time-f.time):.1)+'\n').join(''));
  // Toggle while motion is active: accessibility changes must cancel in-flight animation.
  await page.locator('#grid tbody tr[data-id]').nth(3).click();
  await page.emulateMedia({reducedMotion:'reduce'});await page.waitForTimeout(40);
  observations.reducedActive=await page.locator('#drawer').evaluate(e=>e.getAnimations({subtree:true}).filter(a=>a.playState==='running'&&a.effect.getTiming().duration>1).length);
  assert.equal(observations.reducedActive,0);
  await page.locator('#grid tbody tr[data-id]').nth(4).click();
  assert.equal(await ring.evaluate(e=>+getComputedStyle(e).getPropertyValue('--pct')),await ring.evaluate(e=>+e.style.getPropertyValue('--pct')));
  await page.locator('[data-dtab="fit"]').click();await page.waitForTimeout(40);
  assert.equal(await page.locator('#drawer').evaluate(e=>e.getAnimations({subtree:true}).filter(a=>a.playState==='running'&&a.effect.getTiming().duration>1).length),0);
  assert.deepEqual(errors,[]);assert(writes.every(action=>action==='state'),'Only mocked device-state requests are allowed');
  fs.writeFileSync(out+'/motion-evidence.json',JSON.stringify({...observations,score:actual,recordedFrames:frames.length,errors,writes,fixture:'600 synthetic jobs; external requests blocked'},null,2));
  console.log('Motion checks passed: selection, real score, detail tabs, input focus, divider, real loading state, reduced motion; no canonical writes or browser errors.');
  await context.close();
 }finally{if(browser)await browser.close();await new Promise(r=>server.close(r));}
})().catch(e=>{console.error(e);process.exitCode=1});
