const assert=require('node:assert/strict'),fs=require('fs');
const P=require('../pipeline-policy'),S=require('../pipeline-scoring'),W=require('../apps-script/Code.gs');
assert.equal(fs.readFileSync('pipeline-policy.js','utf8'),fs.readFileSync('apps-script/PipelinePolicy.gs','utf8'));
assert.equal(P.assess({FLEX:'YES'},70).adjustedFit,85);
assert.equal(P.assess({FLEX:'SOFT'},70).adjustedFit,76);
assert.equal(P.assess({FLEX:'NO',FLOOR_STATUS:'CLEARS',TITLE_RULE_STATUS:'PASS'},90).decision,'PURSUE_CANDIDATE');
assert.equal(P.assess({FLEX:'STRICT_NO'},99).decision,'STRICT_HOLD');
assert.equal(P.flex({FLEX:'STRICT_NO',TIM_FLEX_OVERRIDE:'YES'}).blocked,false);
assert.equal(P.flex({}).class,'UNKNOWN');
assert.equal(P.flex({DEGREE_TEXT:'NOT STATED'}).class,'HIGH_FLEX');
assert.equal(P.flex({REQUIREMENTS_REVIEWED:'YES',DEGREE_TEXT:'Bachelors degree or equivalent experience'}).class,'SOFT_FLEX');
const url='https://www.linkedin.com/jobs/view/123?tracking=original';
assert.equal(P.links({payload:{SOURCE:'LinkedIn '+url}}).preferred,url);
const row='1 | TEST | Test Co | Director | MANUAL_RESEARCH | OPEN | - | X | TN | TEST; SOURCE_URL='+url+'; FLEX=NO; SCOPE_FIT_RAW=90';
const out=W.mutateRow(row,{kind:'ENRICH',fields:{SOURCE_URL:'https://company.test/job/123'}});
assert(out.ok);assert(out.after.includes('INITIATING_URL='+url));assert(out.after.includes('ADJUSTED_FIT=80'));
assert.equal(W.mutateRow(out.after,{kind:'ENRICH',fields:{INITIATING_URL:'https://other.test'}}).ok,false);
const high=S.scoreRow({TITLE:'Director',payload:{FIT_SCORE:70,FLEX:'YES'}},S.defaults());
const no=S.scoreRow({TITLE:'Director',payload:{FIT_SCORE:70,FLEX:'NO'}},S.defaults());
assert(high.overall>no.overall);assert.equal(high.parts.experience.rawScore,70);
console.log('PASS FLEX modifiers, strict override, unknown evidence, URL preservation and shared writer policy');
