const W = require('../apps-script/Code.gs');
let fails = 0; const ok = (c, m) => { if (!c) { fails++; console.log('FAIL', m); } else console.log('ok  ', m); };
const R = W.defaultRules();
ok(R.rules.length === 4 && R.rules.every(r => r.id && r.enabled && r.domains.length), 'four default rules, all enabled, each with domain terms');
const c = (rec) => W.classifyNeverConsider(rec, R);
ok(c({ COMPANY: 'Pfizer', EMPLOYER_DOMAIN_HINT: 'pharmaceutical manufacturer' }).ruleId === 'NC-PHARMA', 'pharma primary business excluded');
ok(c({ COMPANY: 'Medtronic', EMPLOYER_DOMAIN_HINT: 'medical device manufacturer' }).ruleId === 'NC-MEDDEV', 'medical device excluded');
ok(c({ COMPANY: 'Coca-Cola Bottling', EMPLOYER_DOMAIN_HINT: 'beverage bottling' }).ruleId === 'NC-FOODBEV', 'beverage excluded');
ok(c({ COMPANY: 'Chick-fil-A', EMPLOYER_DOMAIN_HINT: 'quick service restaurant' }).ruleId === 'NC-FOODSVC', 'restaurant excluded');
ok(!c({ COMPANY: 'Automation Partners', EMPLOYER_DOMAIN_HINT: 'industrial automation supplier serving pharmaceutical plants' }).excluded, 'supplier to pharma NOT excluded');
ok(!c({ COMPANY: 'Conveyor Systems Inc', EMPLOYER_DOMAIN_HINT: 'industrial equipment for the food manufacturing industry customers' }).excluded, 'equipment maker with food customers NOT excluded');
ok(!c({ COMPANY: 'Anduril', TITLE: 'Director, Pharmaceutical Robotics', EMPLOYER_DOMAIN_HINT: 'defense technology' }).excluded, 'keyword in title never triggers a rule');
ok(!c({ COMPANY: 'Unknown Co' }).excluded, 'no hint, no employer match -> not excluded (unknown is not a rejection)');
const custom = W.normRules({ rules: [{ id: 'NC-PHARMA', enabled: false, domains: ['pharmaceutical'] }, { id: 'NC-TOBACCO', enabled: true, domains: ['tobacco'], employers: ['Altria Group, Inc.'] }] });
ok(!W.classifyNeverConsider({ COMPANY: 'Pfizer', EMPLOYER_DOMAIN_HINT: 'pharmaceutical manufacturer' }, custom).excluded, 'disabled rule does not exclude');
ok(W.classifyNeverConsider({ COMPANY: 'Altria Group Inc', EMPLOYER_DOMAIN_HINT: '' }, custom).ruleId === 'NC-TOBACCO', 'new rule with employer list matches by normalized employer name (no code change)');
ok(W.normRules({ garbage: true }).rules.length === 4, 'malformed rules file falls back to defaults');
ok(W.normRules({ rules: [{ nope: 1 }, { id: 'X' }] }).rules.length === 1, 'rules without an id are dropped');
console.log(fails ? ('\n' + fails + ' FAILED') : '\nALL PASS'); process.exit(fails ? 1 : 0);
