/* Browser regression checks; requests use a local test-only writer. */
const {chromium}=require(process.env.PIPELINE_PLAYWRIGHT_MODULE || 'playwright');
const fs=require('fs'),assert=require('assert');
const repo=require('path').resolve(__dirname,'..'),artifacts=process.env.PIPELINE_UI_ARTIFACTS || require('os').tmpdir();
const fixture=fs.readFileSync(repo+'/tests/fixtures/master.sample.txt','utf8').split('\n').map((l,i)=> /^\d+ \|/.test(l)?l+'; SCOUT_RUN_ID=SCOUT-'+(i%3)+'; DISCOVERED_AT_ET=2026-10-0'+(i%2+1)+' 02:30;':l).join('\n');
const rules=fs.readFileSync(repo+'/tests/fixtures/TIM_PIPELINE_RULES_CANONICAL.sample.txt','utf8');
(async()=>{const server=require('http').createServer((req,res)=>{const url=new URL(req.url,'http://localhost');const file=repo+url.pathname;try{res.setHeader('Content-Type',file.endsWith('.js')?'application/javascript':'text/html');res.end(fs.readFileSync(file))}catch(e){res.statusCode=404;res.end('missing')}});await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true,executablePath:process.env.PIPELINE_CHROMIUM || undefined,args:['--no-sandbox']});const page=await browser.newPage({viewport:{width:1440,height:900}});const errors=[],writes=[];
page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>localStorage.setItem('px.cfg',JSON.stringify({url:location.origin+'/writer',key:'test-only'})));
await page.route('**/writer*',async r=>{const req=r.request(),u=new URL(req.url()),a=u.searchParams.get('action');let body={ok:true};if(req.method()==='POST'){writes.push(JSON.parse(req.postData()));}else if(a==='master')body={ok:true,id:'test-master',text:fixture,fetchedAt:new Date().toISOString(),modifiedTime:'2026-10-02T03:00:00Z'};else if(a==='canonical_rules')body={ok:true,text:rules};else if(a==='runs')body={ok:true,runs:[0,1,2].map(n=>({SCOUT_RUN_ID:'SCOUT-'+n,GROSS_FOUND:15,RECEIVED_AT:'2026-10-01T02:30:00Z'}))};else if(a==='state')body={ok:true,state:{}};await r.fulfill({json:body});});
await page.goto('http://127.0.0.1:'+server.address().port+'/pipeline.html');await page.waitForSelector('#grid tbody tr[data-id]');
assert.equal(await page.locator('#dash .chart-svg').count(),2);assert.equal(await page.locator('.map-outline').count(),51);
async function checkSplit(){return page.evaluate(()=>{const d=document.querySelector('#dash'),v=document.querySelector('#view-pipeline'),w=document.querySelector('#worksplit');return {ratio:d.clientHeight/v.clientHeight,overflow:d.scrollHeight-d.clientHeight,workEnd:w.getBoundingClientRect().bottom-viewEnd(v),cards:[...d.children].map(c=>({h:c.clientHeight,sh:c.scrollHeight}))};function viewEnd(x){return x.getBoundingClientRect().bottom}})}
console.log('desktop split',await checkSplit());assert(Math.abs((await checkSplit()).ratio-.35)<.003);assert((await checkSplit()).overflow<=1);
const company=page.locator('th[data-c="COMPANY"]'),handle=company.locator('.resize-handle');let before=await company.evaluate(e=>e.getBoundingClientRect().width),box=await handle.boundingBox();await page.mouse.move(box.x+box.width/2,box.y+8);await page.mouse.down();await page.mouse.move(box.x+box.width/2+90,box.y+8);await page.mouse.up();let after=await company.evaluate(e=>e.getBoundingClientRect().width);assert(Math.abs(after-before-90)<2);assert.equal(await page.locator('#pop').isVisible(),false);box=await handle.boundingBox();await page.mouse.move(box.x+5,box.y+8);await page.mouse.down();await page.mouse.move(box.x-45,box.y+8);await page.mouse.up();after=await company.evaluate(e=>e.getBoundingClientRect().width);assert(Math.abs(after-before-40)<2);await page.reload();await page.waitForSelector('#grid tbody tr[data-id]');assert(Math.abs(await company.evaluate(e=>e.getBoundingClientRect().width)-after)<2);await handle.focus();await page.keyboard.press('ArrowRight');assert(Math.abs(await company.evaluate(e=>e.getBoundingClientRect().width)-after-10)<2);
await page.locator('#grid tbody tr[data-id]').first().click();await page.locator('#edit-state').selectOption('REJECTED_BY_EMPLOYER');assert(await page.locator('#edit-evidence').isVisible());await page.locator('#save-decision').click();assert.match(await page.locator('#edit-status').innerText(),/evidence/);await page.locator('#edit-evidence').fill('Test-only employer notice');await page.locator('#edit-event-date').fill('2026-10-01');await page.locator('#save-decision').click();await page.waitForTimeout(200);const ruling=writes.find(w=>w.action==='ruling');assert(ruling);assert.equal(ruling.ruling.kind,'REJECTED_BY_EMPLOYER');assert.equal(ruling.ruling.eventDate,'2026-10-01');assert.equal(ruling.ruling.evidence,'Test-only employer notice');
await page.locator('[data-dtab="compensation"]').click();assert(!(await page.locator('#d-body').innerText()).includes('bad-credit'));await page.locator('#d-close').click();await page.screenshot({path:artifacts+'/pipeline-desktop.png'});
await page.locator('[data-tab="reports"]').click();assert.equal(await page.locator('#view-reports .chart-svg').count(),6);await page.screenshot({path:artifacts+'/reports-desktop.png'});
await page.locator('[data-tab="quality"]').click();assert.equal(await page.locator('#view-quality .chart-svg').count(),4);await page.screenshot({path:artifacts+'/scout-desktop.png'});
await page.locator('[data-tab="rules"]').click();assert.equal(await page.locator('.rule-section').count(),3);await page.locator('#rules-search').fill('HOME_PIN');assert.equal(await page.locator('.rule-section:visible').count(),1);await page.locator('#rules-search').fill('');await page.locator('#rules-mode').click();assert.equal(await page.locator('#rules-edit').inputValue(),rules);await page.locator('#rules-edit').fill(rules+'\nTEST_DRAFT=unsaved');await page.locator('[data-tab="pipeline"]').click();await page.locator('[data-tab="rules"]').click();assert((await page.locator('#rules-edit').inputValue()).includes('TEST_DRAFT'));await page.locator('#rules-mode').click();await page.screenshot({path:artifacts+'/rules-desktop.png'});
for(const vp of [{width:1366,height:768},{width:1024,height:600},{width:390,height:844},{width:844,height:390}]){await page.setViewportSize(vp);await page.locator('[data-tab="pipeline"]').click();await page.waitForTimeout(100);const split=await checkSplit();console.log('split',vp,split);assert(Math.abs(split.ratio-.35)<.006);assert(split.overflow<=1);assert(split.cards.every(c=>c.sh<=c.h+1), 'Dashboard card content should not clip');assert(Math.abs(split.workEnd)<2);await page.screenshot({path:artifacts+'/pipeline-'+vp.width+'.png'});}
assert.deepEqual(errors,[]);console.log('PASS: resize grow/shrink, persistence, keyboard, rejection submission, compensation, charts, Rules search/source/draft, four viewport splits; no browser errors.');await browser.close();server.close();})().catch(e=>{console.error(e);process.exit(1)});
