/* Browser regression checks; requests use a local test-only writer. */
const {chromium}=require(process.env.PIPELINE_PLAYWRIGHT_MODULE || 'playwright');
const fs=require('fs'),assert=require('assert');
const repo=require('path').resolve(__dirname,'..'),artifacts=process.env.PIPELINE_UI_ARTIFACTS || require('os').tmpdir();
const fixture=fs.readFileSync(repo+'/tests/fixtures/master.sample.txt','utf8').split('\n').map((l,i)=> /^\d+ \|/.test(l)?l+'; SCOUT_RUN_ID=SCOUT-'+(i%3)+'; DISCOVERED_AT_ET=2026-10-0'+(i%2+1)+' 02:30;':l).join('\n');
const rules=fs.readFileSync(repo+'/tests/fixtures/TIM_PIPELINE_RULES_CANONICAL.sample.txt','utf8');
// Navigate the way a user does: the rail on desktop (hover to reveal sub-items), the bottom bar or its More sheet on phones.
async function go(page,tab){const rail=page.locator('#rail');if(await rail.isVisible()){await rail.hover();if((await page.locator('#rail .rail-in').boundingBox()).width<100){await page.locator('#rail [data-group-btn]').first().click();await page.waitForTimeout(250)}const b=page.locator('#rail [data-tab="'+tab+'"], #rail [data-go="'+tab+'"]').first();await b.click();await page.mouse.move(700,450);await page.waitForTimeout(150);return}const bb=page.locator('#bottombar [data-go="'+tab+'"]');if(await bb.count()){await bb.click();await page.waitForTimeout(150);return}await page.locator('#bottombar [data-go="more"]').click();await page.locator('#sheet [data-go="'+tab+'"]').click();await page.waitForTimeout(150)}
(async()=>{const server=require('http').createServer((req,res)=>{const url=new URL(req.url,'http://localhost');const file=repo+url.pathname;try{res.setHeader('Content-Type',file.endsWith('.js')?'application/javascript':'text/html');res.end(fs.readFileSync(file))}catch(e){res.statusCode=404;res.end('missing')}});await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true,executablePath:process.env.PIPELINE_CHROMIUM || undefined,args:['--no-sandbox']});const page=await browser.newPage({viewport:{width:1440,height:900}});const errors=[],writes=[];
page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>localStorage.setItem('px.cfg',JSON.stringify({url:location.origin+'/writer',key:'test-only'})));
await page.route('**/writer*',async r=>{const req=r.request(),u=new URL(req.url()),a=u.searchParams.get('action');let body={ok:true};if(req.method()==='POST'){writes.push(JSON.parse(req.postData()));}else if(a==='master')body={ok:true,id:'test-master',text:fixture,fetchedAt:new Date().toISOString(),modifiedTime:'2026-10-02T03:00:00Z'};else if(a==='canonical_rules')body={ok:true,text:rules};else if(a==='runs')body={ok:true,runs:[0,1,2].map(n=>({SCOUT_RUN_ID:'SCOUT-'+n,GROSS_FOUND:15,RECEIVED_AT:'2026-10-01T02:30:00Z'}))};else if(a==='state')body={ok:true,state:{}};await r.fulfill({json:body});});
await page.goto('http://127.0.0.1:'+server.address().port+'/pipeline.html');await go(page,'pipeline');await page.waitForSelector('#grid tbody tr[data-id]');
assert.equal(await page.locator('#dash .chart-svg').count(),2);assert.equal(await page.locator('.map-outline').count(),51);
async function checkSplit(){return page.evaluate(()=>{const d=document.querySelector('#dash'),v=document.querySelector('#view-pipeline'),w=document.querySelector('#worksplit');return {ratio:d.getBoundingClientRect().height/v.getBoundingClientRect().height,overflow:d.scrollHeight-d.clientHeight,workEnd:w.getBoundingClientRect().bottom-viewEnd(v),cards:[...d.children].map(c=>({h:c.clientHeight,sh:c.scrollHeight}))};function viewEnd(x){return x.getBoundingClientRect().bottom}})}
console.log('desktop split',await checkSplit());assert(Math.abs((await checkSplit()).ratio-.35)<.003);assert((await checkSplit()).overflow<=1);
const company=page.locator('th[data-c="COMPANY"]'),handle=company.locator('.resize-handle');let before=await company.evaluate(e=>e.getBoundingClientRect().width),box=await handle.boundingBox();await page.mouse.move(box.x+box.width/2,box.y+8);await page.mouse.down();await page.mouse.move(box.x+box.width/2+90,box.y+8);await page.mouse.up();let after=await company.evaluate(e=>e.getBoundingClientRect().width);assert(Math.abs(after-before-90)<2);assert.equal(await page.locator('#pop').isVisible(),false);box=await handle.boundingBox();await page.mouse.move(box.x+5,box.y+8);await page.mouse.down();await page.mouse.move(box.x-45,box.y+8);await page.mouse.up();after=await company.evaluate(e=>e.getBoundingClientRect().width);assert(Math.abs(after-before-40)<2);await page.reload();await go(page,'pipeline');await page.waitForSelector('#grid tbody tr[data-id]');assert(Math.abs(await company.evaluate(e=>e.getBoundingClientRect().width)-after)<2);await handle.focus();await page.keyboard.press('ArrowRight');assert(Math.abs(await company.evaluate(e=>e.getBoundingClientRect().width)-after-10)<2);
await page.locator('#grid tbody tr[data-id]').first().click();await page.locator('#edit-state').selectOption('REJECTED_BY_EMPLOYER');assert(await page.locator('#edit-evidence').isVisible());await page.locator('#save-decision').click();assert.match(await page.locator('#edit-status').innerText(),/evidence/);await page.locator('#edit-evidence').fill('Test-only employer notice');await page.locator('#edit-event-date').fill('2026-10-01');await page.locator('#save-decision').click();await page.waitForTimeout(200);const ruling=writes.find(w=>w.action==='ruling');assert(ruling);assert.equal(ruling.ruling.kind,'REJECTED_BY_EMPLOYER');assert.equal(ruling.ruling.eventDate,'2026-10-01');assert.equal(ruling.ruling.evidence,'Test-only employer notice');
await page.locator('[data-dtab="fit"]').click();assert(!(await page.locator('#d-body').innerText()).includes('bad-credit'));assert.match(await page.locator('#d-body').innerText(),/Compensation/i);for(const tab of ['posting','application','documents','history']){await page.locator('[data-dtab="'+tab+'"]').click();assert((await page.locator('#d-body').innerText()).length>20,tab+' tab renders')}assert.equal(await page.locator('#drawer .wh-chips .bpill').count(),1);assert(await page.locator('#ws-cover').isDisabled(),'cover letter drafting stays gated');await page.locator('#ws-next').click();await page.waitForTimeout(150);assert.equal(await page.locator('#grid tr.focus').getAttribute('data-id'),await page.locator('#grid tbody tr[data-id]').nth(1).getAttribute('data-id'),'next steps to the following row');await page.locator('#ws-prev').click();await page.waitForTimeout(150);await page.locator('[data-dtab="overview"]').click();await page.locator('#d-close').click();await page.screenshot({path:artifacts+'/pipeline-desktop.png'});
await go(page,'reports');assert.equal(await page.locator('#view-reports .chart-svg').count(),6);await page.screenshot({path:artifacts+'/reports-desktop.png'});
await go(page,'quality');assert.equal(await page.locator('#view-quality .chart-svg').count(),4);await page.screenshot({path:artifacts+'/scout-desktop.png'});
await go(page,'rules');assert.equal(await page.locator('.rule-section').count(),3);await page.locator('#rules-search').fill('HOME_PIN');assert.equal(await page.locator('.rule-section:visible').count(),1);await page.locator('#rules-search').fill('');await page.locator('#rules-mode').click();assert.equal(await page.locator('#rules-edit').inputValue(),rules);await page.locator('#rules-edit').fill(rules+'\nTEST_DRAFT=unsaved');await go(page,'pipeline');await go(page,'rules');assert((await page.locator('#rules-edit').inputValue()).includes('TEST_DRAFT'));await page.locator('#rules-mode').click();await page.screenshot({path:artifacts+'/rules-desktop.png'});
for(const vp of [{width:1366,height:768},{width:1024,height:600},{width:390,height:844},{width:844,height:390}]){await page.setViewportSize(vp);await go(page,'pipeline');await page.waitForTimeout(100);const split=await checkSplit();console.log('split',vp,split);assert(Math.abs(split.ratio-.35)<.006);assert(split.overflow<=1);assert(split.cards.every(c=>c.sh<=c.h+1), 'Dashboard card content should not clip');assert(Math.abs(split.workEnd)<2);await page.screenshot({path:artifacts+'/pipeline-'+vp.width+'.png'});}
// Map navigation: a table-row selection sweeps to 600%, hover selects labels, wheel and controls preserve focus.
await page.setViewportSize({width:1440,height:900});await page.locator('#grid tbody tr[data-id]').first().click();await page.waitForTimeout(750);
assert.equal(await page.locator('#map-zoom-level').innerText(),'600%');
await page.locator('[data-mapzoom="in"]').click();await page.waitForTimeout(250);assert.equal(await page.locator('#map-zoom-level').innerText(),'750%');
const panStart=await page.locator('#job-map').evaluate(e=>({x:+e.dataset.centerX,y:+e.dataset.centerY})),panRect=await page.locator('#job-map').boundingBox();
await page.mouse.move(panRect.x+20,panRect.y+20);await page.mouse.down();await page.mouse.move(panRect.x+70,panRect.y+40,{steps:8});await page.mouse.up();
assert(+await page.locator('#job-map').getAttribute('data-center-x')<panStart.x);assert(+await page.locator('#job-map').getAttribute('data-center-y')<panStart.y);assert.equal(await page.locator('#map-zoom-level').innerText(),'750%');assert.equal(await page.locator('.job-map.panning').count(),0);
await page.locator('[data-mapaction="recenter"]').click();await page.waitForTimeout(750);assert(Math.abs(+await page.locator('#job-map').getAttribute('data-center-x')-panStart.x)<.01);
const oldCenter=await page.locator('#job-map').getAttribute('data-center-x');await page.locator('#grid tbody tr[data-id]').nth(1).click();await page.waitForFunction(c=>document.getElementById('job-map').dataset.centerX!==c,oldCenter,{timeout:1500});const movingCenter=await page.locator('#job-map').getAttribute('data-center-x');assert.notEqual(await page.locator('#map-zoom-level').innerText(),'600%','the sweep is animated, not a jump');await page.waitForFunction(()=>document.getElementById('map-zoom-level').textContent==='600%',null,{timeout:2000});await page.waitForTimeout(120);assert.equal(await page.locator('#map-zoom-level').innerText(),'600%');assert.notEqual(await page.locator('#job-map').getAttribute('data-center-x'),oldCenter);assert.notEqual(movingCenter,oldCenter);
await page.locator('#map-zoom-level').click();await page.waitForTimeout(750);assert.equal(await page.locator('#map-zoom-level').innerText(),'100%');
await page.locator('[data-mapzoom="in"]').click();await page.locator('[data-mapzoom="in"]').click();await page.locator('#grid tbody tr[data-id]').first().click();await page.waitForTimeout(750);assert.equal(await page.locator('#map-zoom-level').innerText(),'600%');await page.locator('#map-zoom-level').click();await page.waitForTimeout(750);
await page.route('**/geocoding-api.open-meteo.com/**',r=>r.fulfill({json:{results:[]}}));await page.locator('[data-mapfilter="visible"]').click();await page.waitForTimeout(150);assert(await page.locator('.map-target').count()>1);assert.equal(await page.locator('.map-target-label').count(),0);
const point=page.locator('.map-target[aria-label="Huntsville, AL"]');const pinBounds=await point.boundingBox();await page.mouse.move(pinBounds.x+pinBounds.width/2,pinBounds.y+pinBounds.height/2);assert.equal(await page.locator('.map-target-label strong').innerText(),'Huntsville, AL');assert.equal(await page.locator('.map-target-label .map-company').innerText(),'Company-08');assert.match(await page.locator('.map-target-label .map-role').innerText(),/Sr Director/);assert.match(await page.locator('.map-target-label .map-salary').innerText(),/163/);await page.locator('#crumb').hover();assert.equal(await page.locator('.map-target-label').count(),0);
const mapRect=await page.locator('#job-map').boundingBox();await page.mouse.move(mapRect.x+mapRect.width/2,mapRect.y+mapRect.height/2);await page.mouse.wheel(0,-150);await page.waitForTimeout(250);assert(Number(await page.locator('#job-map').getAttribute('data-zoom'))>1);await page.mouse.wheel(0,150);await page.waitForTimeout(250);assert.equal(await page.locator('#map-zoom-level').innerText(),'100%');
await page.locator('[data-mapaction="reset"]').click();await page.waitForTimeout(750);assert.equal(await page.locator('#map-zoom-level').innerText(),'100%');assert.equal(await page.locator('#job-map').getAttribute('data-center-x'),'480.000');
const initialPins=await page.locator('.map-target').evaluateAll(es=>es.map(e=>e.getAttribute('aria-label')).sort());
await page.locator('#gridwrap').evaluate(e=>e.scrollTop=e.scrollHeight);await page.waitForTimeout(300);
const scrolledPins=await page.locator('.map-target').evaluateAll(es=>es.map(e=>e.getAttribute('aria-label')).sort());assert.deepEqual(scrolledPins,initialPins,'Current View pins must include the full filtered table, not only the viewport');assert.match(await page.locator('#map-sub').innerText(),/21 rows in current view/);
await page.locator('#gridwrap').evaluate(e=>e.scrollTop=0);await page.waitForTimeout(300);assert.deepEqual(await page.locator('.map-target').evaluateAll(es=>es.map(e=>e.getAttribute('aria-label')).sort()),initialPins);
await page.locator('[data-mapfilter="selected"]').click();await page.screenshot({path:artifacts+'/map-zoom-desktop.png'});
// Group map filters use all matching master rows, independently of the table preset.
await page.locator('[data-mapfilter="applied"]').click();await page.waitForTimeout(250);assert.match(await page.locator('#map-sub').innerText(),/3 jobs · Applied/);assert(await page.locator('.map-target').count()>0);
await page.locator('[data-mapfilter="active"]').click();await page.waitForTimeout(250);assert.match(await page.locator('#map-sub').innerText(),/Active work/);
await page.locator('[data-mapfilter="scout"]').click();await page.waitForTimeout(250);assert.equal(await page.locator('.map-target').count(),0);assert.match(await page.locator('#job-map').innerText(),/No mapped jobs/);
await page.locator('[data-mapfilter="ready"]').click();await page.waitForTimeout(250);assert.match(await page.locator('#map-sub').innerText(),/6 jobs · Ready/);
await page.locator('[data-mapfilter="selected"]').click();await page.waitForTimeout(250);
// Pin selection reveals a row hidden by table filters, then blank map restores the prior view.
await page.locator('#d-close').click();await page.locator('[data-p="APPLY_NOW"]').click();await page.locator('[data-mapfilter="applied"]').click();await page.locator('[data-mapaction="reset"]').click();await page.waitForTimeout(750);
const beforeMap=await page.locator('#job-map').evaluate(e=>({x:e.dataset.centerX,y:e.dataset.centerY,zoom:e.dataset.zoom}));
await page.locator('.map-target[aria-label="Cleveland, TN"]').click();await page.waitForTimeout(750);
assert.equal(await page.locator('#grid tr.focus').getAttribute('data-id'),'V2X-ECDC06118753');assert.match(await page.locator('#d-title').innerText(),/Company-13/);assert.equal(await page.locator('[data-mapfilter="selected"]').getAttribute('aria-pressed'),'true');assert.equal(await page.locator('[data-p="ALL"]').getAttribute('class'),'chip on');
const selectedBounds=await page.locator('#grid tr.focus').boundingBox(),tableBounds=await page.locator('#gridwrap').boundingBox();assert(selectedBounds.y>=tableBounds.y&&selectedBounds.y+selectedBounds.height<=tableBounds.y+tableBounds.height+1);
await page.locator('#job-map').click({position:{x:3,y:3}});await page.waitForTimeout(750);assert.equal(await page.locator('[data-mapfilter="applied"]').getAttribute('aria-pressed'),'true');assert(await page.locator('[data-p="APPLY_NOW"]').evaluate(e=>e.classList.contains('on')));assert.equal(await page.locator('#grid tr.focus').count(),0);assert.equal(await page.locator('#drawer').evaluate(e=>e.classList.contains('on')),false);assert.deepEqual(await page.locator('#job-map').evaluate(e=>({x:e.dataset.centerX,y:e.dataset.centerY,zoom:e.dataset.zoom})),beforeMap);
// Clicking a pin while zoomed must survive pointer capture; dragging must not navigate.
await page.locator('[data-mapfilter="ready"]').click();await page.waitForTimeout(200);await page.locator('[data-mapzoom="in"]').click();await page.waitForTimeout(250);await page.locator('.map-target[aria-label="Huntsville, AL"]').click();assert.equal(await page.locator('#map-job-picker [data-maprow]').count(),2);await page.locator('[data-maprow="V2X-A4CCD49EE686"]').click();await page.waitForTimeout(750);assert.equal(await page.locator('#grid tr.focus').getAttribute('data-id'),'V2X-A4CCD49EE686');
const dragBounds=await page.locator('#job-map').boundingBox();await page.mouse.move(dragBounds.x+5,dragBounds.y+5);await page.mouse.down();await page.mouse.move(dragBounds.x+45,dragBounds.y+15,{steps:5});await page.mouse.up();assert.equal(await page.locator('[data-mapfilter="selected"]').getAttribute('aria-pressed'),'true');
await page.locator('#job-map').click({position:{x:3,y:3}});await page.waitForTimeout(750);assert.equal(await page.locator('[data-mapfilter="ready"]').getAttribute('aria-pressed'),'true');assert.equal(await page.locator('#map-zoom-level').innerText(),'125%');
await page.locator('[data-p="ALL"]').click();await page.locator('[data-mapfilter="visible"]').click();await page.waitForTimeout(250);
// Touch context checks: target labels stay visible, mobile tracks are separate, landscape remains usable.
const touch=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});
const mobile=await touch.newPage();mobile.on('pageerror',e=>errors.push(e.message));
await touch.addInitScript(()=>{localStorage.setItem('px.cfg',JSON.stringify({url:location.origin+'/writer',key:'test-only'}));localStorage.setItem('px.colWidths',JSON.stringify({COMPANY:400}))});
await mobile.route('**/writer*',async r=>{const a=new URL(r.request().url()).searchParams.get('action');await r.fulfill({json:a==='master'?{ok:true,id:'test',text:fixture,fetchedAt:new Date().toISOString()}:a==='canonical_rules'?{ok:true,text:rules}:a==='state'?{ok:true,state:{}}:{ok:true}})});
await mobile.route('**/geocoding-api.open-meteo.com/**',r=>r.fulfill({json:{results:[]}}));
await mobile.goto('http://127.0.0.1:'+server.address().port+'/pipeline.html');await go(mobile,'pipeline');await mobile.waitForSelector('#grid tbody tr[data-id]');
assert.equal(Math.round(await mobile.locator('th[data-c="COMPANY"]').evaluate(e=>e.getBoundingClientRect().width)),140);
assert.equal(await mobile.locator('#job-map-card').evaluate(e=>getComputedStyle(e).backgroundColor),'rgb(0, 0, 0)');
assert(await mobile.locator('.preset-list').evaluate(e=>e.scrollWidth>e.clientWidth));
const touchDriver=await touch.newCDPSession(mobile);
async function touchResize(col,delta){const th=mobile.locator('th[data-c="'+col+'"]'),grip=th.locator('.resize-handle'),b=await grip.boundingBox(),before=await th.evaluate(e=>e.getBoundingClientRect().width),x=b.x+b.width/2,y=b.y+b.height/2;await touchDriver.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y}]});await touchDriver.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x+delta,y}]});await touchDriver.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});return {before,after:await th.evaluate(e=>e.getBoundingClientRect().width)}}
for(const col of ['NEW','COMPANY']){let size=await touchResize(col,32);assert(Math.abs(size.after-size.before-32)<2,col+' must resize with touch');size=await touchResize(col,-16);assert(Math.abs(size.after-size.before+16)<2,col+' must shrink with touch')}
await mobile.reload();await go(mobile,'pipeline');await mobile.waitForSelector('#grid tbody tr[data-id]');assert.equal(Math.round(await mobile.locator('th[data-c="NEW"]').evaluate(e=>e.getBoundingClientRect().width)),60);assert.equal(Math.round(await mobile.locator('th[data-c="COMPANY"]').evaluate(e=>e.getBoundingClientRect().width)),156);
await mobile.locator('#grid tbody tr[data-id]').first().tap();await mobile.waitForSelector('.map-target-label');
assert.equal(await mobile.locator('.map-target-label strong').innerText(),'Huntsville, AL');
assert(await mobile.locator('.map-target').first().getAttribute('aria-label'));
const labelBounds=await mobile.locator('.map-target-label').boundingBox(),mapBounds=await mobile.locator('#job-map').boundingBox();assert(labelBounds.x>=mapBounds.x && labelBounds.x+labelBounds.width<=mapBounds.x+mapBounds.width+1);
const drawerBounds=await mobile.locator('#drawer').boundingBox(),workBounds=await mobile.locator('#worksplit').boundingBox();assert(Math.abs(drawerBounds.y-workBounds.y)<1,'Phone detail drawer must leave the dashboard visible');
await mobile.waitForTimeout(750);assert.equal(await mobile.locator('#map-zoom-level').innerText(),'600%');await mobile.screenshot({path:artifacts+'/mobile-map-target.png'});
await mobile.locator('.map-target').first().tap();await mobile.waitForTimeout(750);assert.equal(await mobile.locator('#grid tr.focus').getAttribute('data-id'),'V2X-A4CCD49EE686');await mobile.locator('#job-map').tap({position:{x:3,y:3}});await mobile.waitForTimeout(750);assert.equal(await mobile.locator('[data-mapfilter="selected"]').getAttribute('aria-pressed'),'true','a stray touch on the map keeps the selected job (see tests/mobile.browser.js)');assert(await mobile.evaluate(()=>document.getElementById('drawer').classList.contains('on')));await mobile.locator('[data-mapfilter="selected"]').tap();await mobile.locator('#d-close').tap();await mobile.waitForTimeout(300);await mobile.locator('#grid tbody tr[data-id]').first().tap();await mobile.waitForTimeout(750);
await mobile.locator('#edit-state').selectOption('REJECTED_BY_EMPLOYER');assert.equal(await mobile.locator('#edit-state').evaluate(e=>getComputedStyle(e).fontSize),'16px');await mobile.locator('#d-close').tap();
await mobile.setViewportSize({width:844,height:390});await mobile.waitForTimeout(150);await mobile.locator('#grid tbody tr[data-id]').first().tap();await mobile.waitForSelector('.map-target-label');
{const dr=await mobile.locator('#drawer').boundingBox(),wk=await mobile.locator('#worksplit').boundingBox(),vw=await mobile.locator('#view-pipeline').boundingBox();assert(Math.abs(dr.y-wk.y)<1&&Math.abs(dr.width-wk.width)<1,'landscape phone: the job panel covers the table and leaves the band visible');assert(dr.y+dr.height<=vw.y+vw.height+1)}
assert(await mobile.locator('#dash').evaluate(e=>e.scrollHeight<=e.clientHeight+1));
await mobile.screenshot({path:artifacts+'/mobile-map-landscape.png'});await touch.close();
// Charts filter the main table, carry a clearable active state, and support keyboard selection.
await page.setViewportSize({width:1440,height:900});await go(page,'pipeline');
const readyBar=page.locator('svg[aria-label="Next actions"] [aria-label="Filter table: Ready"]');await readyBar.click();assert.equal(await page.locator('#grid tbody tr[data-id]').count(),6);assert.equal(await readyBar.getAttribute('aria-pressed'),'true');assert(await page.locator('#chart-filter-chip').isVisible());await page.locator('#chart-filter-chip').click();assert.equal(await page.locator('#grid tbody tr[data-id]').count(),21);
const fitBar=page.locator('svg[aria-label="Research gaps"] [aria-label="Filter table: FLEX unresolved"]');const fitIds=JSON.parse(await fitBar.getAttribute('data-chart-filter')).ids;await fitBar.focus();await page.keyboard.press('Enter');assert.deepEqual((await page.locator('#grid tbody tr[data-id]').evaluateAll(es=>es.map(e=>e.dataset.id))).sort(),fitIds.sort());await page.locator('#chart-filter-chip').click();
await go(page,'reports');const payBin=page.locator('[aria-label="Filter table: $200–249k"]');const payIds=JSON.parse(await payBin.getAttribute('data-chart-filter')).ids;await payBin.click();assert(await page.locator('#view-pipeline').isVisible());assert.deepEqual((await page.locator('#grid tbody tr[data-id]').evaluateAll(es=>es.map(e=>e.dataset.id))).sort(),payIds.sort());await page.locator('#chart-filter-chip').click();
await go(page,'reports');const unknownPay=page.locator('[aria-label="Filter table: Unknown"]');await unknownPay.click();assert.equal(await page.locator('#grid tbody tr[data-id]').count(),10);await page.locator('#chart-filter-chip').click();
await go(page,'quality');const scoutPart=page.locator('#view-quality [data-chart-filter]').first(),scoutIds=JSON.parse(await scoutPart.getAttribute('data-chart-filter')).ids;await scoutPart.click();assert.deepEqual((await page.locator('#grid tbody tr[data-id]').evaluateAll(es=>es.map(e=>e.dataset.id))).sort(),scoutIds.sort());await page.locator('#chart-filter-chip').click();

const mapControls=await page.locator('#mapfilters').boundingBox(),lastMapControl=await page.locator('[data-mapfilter="ready"]').boundingBox();assert(mapControls.x+mapControls.width-lastMapControl.x-lastMapControl.width<15,'Map controls should align to right edge');
// Operator controls: default Today, confidence labels, comparison, keyboard preparation, density persistence.
await go(page,'pipeline');assert(await page.locator('#dash .decide').count()>=7,'the decide strip carries the Today counts');assert.match(await page.locator('#dash .decide-strip').innerText(),/Stalled 72h/i);await page.locator('#dash [data-decide="ready"]').click();await page.waitForTimeout(150);assert.equal(await page.locator('#dash [data-decide="ready"].on').count(),1,'a decide tile applies its preset and lights up');assert.equal(await page.locator('#presets .chip.on').getAttribute('data-p'),'APPLY_NOW');await page.screenshot({path:artifacts+'/operator-decide.png'});await page.locator('#presets .chip[data-p="ALL"]').click();await page.waitForTimeout(150);assert.equal(await page.locator('#dash .decide.on').count(),0);await page.reload();await page.waitForSelector('#dash .decide-strip');await go(page,'pipeline');await page.locator('#grid tbody tr[data-id]').first().click();await page.locator('#compare-role').click();await page.locator('#d-close').click();await page.locator('#grid tbody tr[data-id]').nth(1).click();await page.locator('#compare-role').click();await page.locator('#compare-open').click();assert.equal(await page.locator('#compare-dialog th [data-compare-remove]').count(),2);await page.screenshot({path:artifacts+'/operator-compare.png'});assert.match(await page.locator('#compare-dialog').innerText(),/Degree \/ FLEX/i);await page.locator('#compare-close').click();await page.locator('#crumb').click();await page.keyboard.press('3');assert.equal(await page.locator('#edit-state').inputValue(),'DECLINED_BY_TIM');assert.equal(writes.filter(w=>w.action==='ruling').length,1,'Shortcut must not submit a write');await page.locator('#d-close').click();const initialHeight=await page.locator('#grid tbody tr').first().evaluate(e=>e.getBoundingClientRect().height);await page.locator('#density-toggle').click();assert((await page.locator('#grid tbody tr').first().evaluate(e=>e.getBoundingClientRect().height))>initialHeight);await page.reload();await go(page,'pipeline');assert.equal(await page.locator('body').getAttribute('data-density'),'comfortable');await page.locator('#density-toggle').click();await page.locator('[data-p="MAINTENANCE"]').click();assert.equal(await page.locator('#grid tbody tr[data-id]').count(),8);await page.locator('[data-p="ALL"]').click();
// Manual intake saves URL drafts through a shared API, preserving application claims and duplicate identity.
const intakeCore=require('../netlify/lib/manual-intake.cjs'),queue=new Map();let version=0;
const store={get:async k=>queue.get(k)?.data||null,getWithMetadata:async k=>queue.get(k)||null,setJSON:async(k,data,o={})=>{var old=queue.get(k);if(o.onlyIfNew&&old||o.onlyIfMatch&&old?.etag!==o.onlyIfMatch)return {modified:false};queue.set(k,{data:JSON.parse(JSON.stringify(data)),etag:String(++version)});return {modified:true}},async *list(){yield {blobs:[...queue.keys()].filter(k=>k.startsWith('items/')).map(key=>({key}))}}};
const intake=intakeCore.createService({store,readMaster:async()=>({rows:[]})});
await page.route('**/api/manual-intake*',async r=>{var b=r.request().method()==='POST'?JSON.parse(r.request().postData()):{};try{await r.fulfill({json:await intake(b.action||'list',b)})}catch(e){await r.fulfill({json:{ok:false,error:e.message},status:400})}});
await go(page,'intake');await page.locator('#intake-add').click();await page.locator('#intake-form [name="url"]').fill('https://jobs.example.org/role/123?utm_source=test');await page.locator('#intake-form [name="company"]').fill('Manual test company');await page.locator('#intake-form [name="applicationStatus"]').selectOption('APPLIED');await page.locator('#intake-form [name="notes"]').fill('User research lead; verify pay.');await page.locator('#intake-submit').click();await page.waitForSelector('[data-intake-id]');assert.equal(await page.locator('[data-intake-id]').count(),1);assert.match(await page.locator('.intake-table').innerText(),/Already applied/);assert.match(await page.locator('.intake-table').innerText(),/Application date unknown/);assert.match(await page.locator('.intake-status').innerText(),/QUEUED/);
await page.locator('#intake-add').click();await page.locator('#intake-form [name="url"]').fill('https://jobs.example.org/role/123');await page.locator('#intake-submit').click();await page.waitForFunction(()=>!document.querySelector('#intake-dialog'));assert.equal(await page.locator('[data-intake-id]').count(),1);assert.match(await page.locator('.intake-message').innerText(),/no duplicate/);await page.screenshot({path:artifacts+'/manual-intake-desktop.png'});
await page.setViewportSize({width:390,height:844});await page.locator('#intake-add').click();assert((await page.locator('#intake-dialog').boundingBox()).width<=390);assert.equal(await page.locator('#intake-form [name="url"]').evaluate(e=>getComputedStyle(e).fontSize),'16px');await page.screenshot({path:artifacts+'/manual-intake-mobile.png'});await page.locator('#intake-cancel').click();
const locked=await browser.newPage();let publicReads=0;await locked.route('**/api/master*',async r=>{publicReads++;await r.fulfill({json:{ok:false}})});await locked.goto('http://127.0.0.1:'+server.address().port+'/pipeline.html');await locked.waitForSelector('#cfg-url');assert.equal(publicReads,0);assert.equal(await locked.locator('#grid tbody tr[data-id]').count(),0);assert.match(await locked.locator('#view-settings').innerText(),/Not configured/);await locked.close();assert.deepEqual(errors,[]);console.log('PASS: resize grow/shrink, persistence, keyboard, rejection submission, compensation, charts, Rules search/source/draft, four viewport splits, chart filters/clear/keyboard, priority job selection, right-aligned map controls; no browser errors.');await browser.close();server.close();})().catch(e=>{console.error(e);process.exit(1)});
