'use strict';
const crypto=require('node:crypto');
const ACTIVE=['QUEUED','RESEARCHING','NEEDS_INFO','FAILED'];
const TERMINAL=['ADDED','EXISTING','EXCLUDED'];
function clean(v,max=400){return String(v??'').trim().slice(0,max)}
function normalizeUrl(value){let u;try{u=new URL(clean(value,2000))}catch{throw new Error('Enter a complete job URL beginning with https://')}if(!['https:','http:'].includes(u.protocol)||u.username||u.password||!u.hostname.includes('.')||/^(localhost|127\.|10\.|192\.168\.|169\.254\.)/i.test(u.hostname))throw new Error('Enter a public http or https job link');u.hash='';for(const k of [...u.searchParams.keys()])if(/^utm_|^(trk|trackingId|ref|referrer|source|src)$/i.test(k))u.searchParams.delete(k);u.hostname=u.hostname.toLowerCase().replace(/^www\./,'');u.searchParams.sort();return u.toString().replace(/\/$/,'')}
function jobId(url){return 'MI-'+crypto.createHash('sha256').update(normalizeUrl(url)).digest('hex').slice(0,24).toUpperCase()}
function appliedStatus(v){return ['APPLIED','NOT_APPLIED','UNSURE'].includes(v)?v:'UNSURE'}
function validDate(v){v=clean(v,10);if(!v)return '';if(!/^\d{4}-\d{2}-\d{2}$/.test(v)||!Number.isFinite(Date.parse(v))||new Date(v).toISOString().slice(0,10)!==v)throw new Error('Applied date must be a real YYYY-MM-DD date');return v}
function summary(items){const counts={TOTAL:items.length,WAITING:0,RESEARCHING:0,NEEDS_INFO:0,IN_MASTER:0,EXCLUDED:0,FAILED:0};items.forEach(x=>{if(ACTIVE.includes(x.status))counts.WAITING++;if(x.status==='RESEARCHING')counts.RESEARCHING++;if(x.status==='NEEDS_INFO')counts.NEEDS_INFO++;if(['ADDED','EXISTING'].includes(x.status))counts.IN_MASTER++;if(x.status==='EXCLUDED')counts.EXCLUDED++;if(x.status==='FAILED')counts.FAILED++});return counts}
function publicItem(item){const result=JSON.parse(JSON.stringify(item));if(result.lease)delete result.lease.token;return result}
function sourceMatch(item,row){let urls=[row.payload?.SOURCE_URL,row.payload?.MANUAL_INTAKE_URL,row.payload?.SOURCE].filter(Boolean);if(urls.some(u=>{try{return normalizeUrl(u)===normalizeUrl(item.url)}catch{return false}}))return true;const r=item.research||{},norm=s=>clean(s).toLowerCase().replace(/[^a-z0-9]/g,'');if(!r.identityVerified||!r.sources?.length)return false;if(norm(r.company)!==norm(row.COMPANY)||norm(r.title)!==norm(row.TITLE))return false;return !r.reqId||!row.REQ||row.REQ==='UNCAPTURED'||norm(r.reqId)===norm(row.REQ)}
function createService({store,readMaster,now=()=>new Date().toISOString()}){
 const key=id=>{if(!/^MI-[A-F0-9]{24}$/.test(id||''))throw new Error('Invalid intake ID');return 'items/'+id};
 async function save(id,change){for(let n=0;n<4;n++){const old=await store.getWithMetadata(key(id),{type:'json'});if(!old)throw new Error('Submission not found');const data=change(JSON.parse(JSON.stringify(old.data)));data.updatedAt=now();const saved=await store.setJSON(key(id),data,{onlyIfMatch:old.etag});if(saved.modified)return data}throw new Error('Submission changed during this request; refresh and retry')}
 function history(item,message,actor){item.history=(item.history||[]).concat({at:now(),actor:clean(actor||'TIM',40),message:clean(message,1000)}).slice(-60)}
 function requireLease(item,body){if(!item.lease?.token||!body.token||item.lease.token!==body.token||Date.parse(item.lease.until)<=Date.parse(now()))throw new Error('Research lease expired or changed; claim the item again')}
 async function list(){const found=[];for await(const page of store.list({prefix:'items/',paginate:true}))for(const blob of page.blobs){const item=await store.get(blob.key,{type:'json'});if(item)found.push(item)}found.sort((a,b)=>b.submittedAt.localeCompare(a.submittedAt));let masterRows=[];if(found.some(i=>i.primaryId)){const master=await readMaster();masterRows=master.rows}
  const items=found.map(item=>{const result=publicItem(item),row=masterRows.find(r=>r.id===item.primaryId);if(row){result.masterBucket=row.BUCKET;result.masterStage=row.BUCKET==='SCOUT_INTAKE'||row.BUCKET==='DISCOVERY_LEAD'?Object.keys(row.payload||{}).some(k=>/^(CLAUDE_|ANALYSIS_|PROPOSED_)/.test(k))?'Awaiting Forge verification':'Awaiting Claude analysis':row.BUCKET==='MANUAL_RESEARCH'?'Further research needed':row.BUCKET.replace(/_/g,' ').toLowerCase()}return result});return {ok:true,items,counts:summary(items),worker:await store.get('worker/health',{type:'json'}),checkedAt:now()}}
 return async function handle(action,body={}){
  if(action==='list')return list();
  if(action==='submit'){
   const url=normalizeUrl(body.url),id=jobId(url),application=appliedStatus(body.applicationStatus),date=validDate(body.appliedDate),hints={company:clean(body.company),title:clean(body.title),location:clean(body.location),reqId:clean(body.reqId)},notes=clean(body.notes,4000),stamp=now();
   const item={id,url,hints,notes,applicationStatus:application,appliedDate:date,status:'QUEUED',phase:'Waiting for identity research',submittedAt:stamp,updatedAt:stamp,submittedBy:'TIM',attempts:0,primaryId:'',history:[{at:stamp,actor:'TIM',message:'Job link submitted for AI research'}]};
   if((await store.setJSON(key(id),item,{onlyIfNew:true})).modified)return {ok:true,item:publicItem(item),duplicate:false};
   const existing=await save(id,old=>{if(notes&&notes!==old.notes)old.notes=clean(old.notes+'\n'+notes,6000);Object.keys(hints).forEach(k=>{if(hints[k])old.hints[k]=hints[k]});if(application==='APPLIED'&&old.applicationStatus!=='APPLIED'){old.applicationStatus='APPLIED';old.appliedDate=date;if(TERMINAL.includes(old.status)){old.status='QUEUED';old.phase='Update application history'}}else if(date&&!old.appliedDate)old.appliedDate=date;history(old,'Same job link resubmitted; existing queue item retained','TIM');return old});return {ok:true,item:publicItem(existing),duplicate:true};
  }
  if(action==='worker_ping'){const worker={at:now(),actor:clean(body.actor||'FORGE',40),state:clean(body.state||'CHECKING',40),note:clean(body.note,800)};await store.setJSON('worker/health',worker);return {ok:true,worker}}
  if(action==='get'){const item=await store.get(key(body.id),{type:'json'});if(!item)throw new Error('Submission not found');return {ok:true,item:publicItem(item)}}
  if(action==='retry'){const item=await save(body.id,item=>{if(!['FAILED','NEEDS_INFO','EXCLUDED'].includes(item.status))throw new Error('This item is already queued, processing, or in the master');item.status='QUEUED';item.phase='Waiting for another research pass';delete item.lease;history(item,'Research retry requested','TIM');return item});return {ok:true,item:publicItem(item)}}
  if(action==='claim'){const token=crypto.randomUUID();const item=await save(body.id,item=>{if(!ACTIVE.includes(item.status))throw new Error('Item already completed');if(item.lease&&Date.parse(item.lease.until)>Date.parse(now()))throw new Error('Another worker is researching this item');item.lease={token,actor:clean(body.actor||'FORGE',40),until:new Date(Date.parse(now())+90*60000).toISOString()};item.status='RESEARCHING';item.phase='Verifying job identity and source';item.attempts++;history(item,item.phase,item.lease.actor);return item});return {ok:true,token,item:publicItem(item)}}
  if(action==='progress'){const item=await save(body.id,item=>{requireLease(item,body);if(!['RESEARCHING','NEEDS_INFO','FAILED','EXCLUDED'].includes(body.status||'RESEARCHING'))throw new Error('Use link with master readback to finish admission');if(body.status==='EXCLUDED'&&!clean(body.ruleId))throw new Error('Excluded items need the actual canonical rule ID');item.status=body.status||'RESEARCHING';item.phase=clean(body.phase||item.phase,200);item.detail=clean(body.detail,2500);if(body.ruleId)item.ruleId=clean(body.ruleId,80);if(body.research){const r=body.research;item.research={company:clean(r.company),title:clean(r.title),location:clean(r.location),reqId:clean(r.reqId),identityVerified:r.identityVerified===true,sources:(Array.isArray(r.sources)?r.sources:[]).slice(0,10).map(s=>({url:normalizeUrl(s.url),note:clean(s.note,1000)})),facts:r.facts&&typeof r.facts==='object'?JSON.parse(JSON.stringify(r.facts)):{} }}if(item.status!=='RESEARCHING')delete item.lease;history(item,item.phase+(item.detail?': '+item.detail:''),body.actor||'FORGE');return item});return {ok:true,item:publicItem(item)}}
  if(action==='link'){const master=await readMaster(),row=master.rows.find(r=>r.id===body.primaryId);if(!row)throw new Error('Canonical PRIMARY_ID not found in fresh master readback');const item=await save(body.id,item=>{requireLease(item,body);if(!sourceMatch(item,row))throw new Error('Master identity does not match this submission; verify the exact role before linking');if(item.applicationStatus==='APPLIED'&&!['APPLIED','REJECTED_BY_EMPLOYER'].includes(row.BUCKET))throw new Error('Already-applied claim has not been preserved in the master; apply the protected state through the writer first');item.primaryId=row.id;item.status=body.existing===true?'EXISTING':'ADDED';item.phase=body.existing===true?'Linked to existing canonical row':'Added through verified writer intake';item.masterBucket=row.BUCKET;item.detail=clean(body.detail,2500);delete item.lease;history(item,item.phase+' · '+row.id,body.actor||'FORGE');return item});return {ok:true,item:publicItem(item),readbackVerified:true}}
  throw new Error('Unsupported manual intake action');
 }
}
module.exports={createService,normalizeUrl,jobId,summary,sourceMatch};
